version: '3'
tasks:
  all:
    deps:
      - test
      - build
      - install

  test:
    cmds:
      - go test ./... -v

  build:
    dir: cmd/weaver
    cmds:
      - go build -o ../../weaver .

  install:
    dir: cmd/weaver
    cmds:
      - go install .
