version: '3'
tasks:
  all:
    deps:
      - test
      - install

  test:
    cmds:
      - go test ./...

  build:
    dir: cmd/weaver
    cmds:
      - go build -o ../../weaver .

  install:
    dir: cmd/weaver
    cmds:
      - go install .

  slides:
    deps:
      - server
      - slides-dev

  slides-dev:
    dir: slides
    cmds:
      - pnpm dev

  server:
    dir: cmd/server
    cmds:
      - go run main.go
