version: '3'
tasks:
  gen-node-bench:
    dir: node
    cmds:
      - ../load_test.sh 'pm2 start main.js -i {{.CPUs}} --no-daemon' 3001 --pm2

  gen-weaver-bench:
    dir: weaver
    env:
      GOMAXPROCS: '{{.CPUs}}'
    cmds:
      - ../load_test.sh 'weaver run main.wvr' 8080

  gen-python-bench:
    dir: python
    cmds:
      - ../load_test.sh 'pipenv run gunicorn --workers {{.CPUs}} --bind 0.0.0.0:3003 main:app' 3003 --gunicorn

  plot:
    cmds:
      - python3 genplot.py weaver node python --output-dir {{.OUT}}

  bench:
    cmds:
      - task: gen-node-bench
        vars:
          CPUs: '{{.CPUs}}'
      - task: gen-weaver-bench
        vars:
          CPUs: '{{.CPUs}}'
      - task: gen-python-bench
        vars:
          CPUs: '{{.CPUs}}'

  gen-report:
    cmds:
      # - task: bench
      #   vars:
      #     CPUs: 1 
      # - task: plot
      #   vars:
      #     OUT: plots-cpu-1
      - task: bench
        vars:
          CPUs: 8 
      - task: plot
        vars:
          OUT: plots-cpu-8
      - task: bench
        vars:
          CPUs: 16
      - task: plot
        vars:
          OUT: plots-cpu-16
